Repository VKCOM/icons, pull requests merged in 2023-07, with the labels that each got.

#638 Fix path to docs build results for github-pages-deploy action
  .github/workflows/publish_icons.yml
Labels: bug, github_actions

#640 Include src/svg into @vkontakte/icons package
  packages/icons/.npmignore
  packages/icons/package.json
Labels: bug

#641 dependabot: use groups; set all schedule to weekly
  .github/dependabot.yml
Labels: dependencies
